kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod-admin
rules:
- apiGroups: [""]
  resources: ["services", "pods", "deployments"]
  verbs: ["get", "watch", "list", "create"]
