apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 3
  labels:
    app: falcoeye-streaming
  name: falcoeye-streaming
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: falcoeye-streaming
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: falcoeye-streaming
    spec:
      containers:
        - name: falcoeye-streaming
          image: falcoeye-streaming:latest
          imagePullPolicy: IfNotPresent
          env:
              - name: FLASK_CONFIG
                value: development
              - name: FLASK_APP
                value: falcoeye
              - name: STREAMING_USER
                valueFrom:
                  secretKeyRef:
                    key: user
                    name: streaming-credentials
              - name: STREAMING_PASSWORD
                valueFrom:
                  secretKeyRef:
                    key: password
                    name: streaming-credentials
              - name: TEMPORARY_DATA_PATH
                value: /falcoeye-temp/
              - name: DEPLOYMENT
                value: k8s  
          volumeMounts:
            - mountPath: /falcoeye-temp/
              name: falcoeye-volume-mount
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File   
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: falcoeye-volume-mount
          persistentVolumeClaim:
            claimName: falcoeye-temp-pvc
