apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 3
  labels:
    app: falcoeye-workflow
  name: falcoeye-workflow
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: falcoeye-workflow
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: falcoeye-workflow
    spec:
      containers:
      - env:
          - name: FLASK_CONFIG
            value: development
          - name: FLASK_APP
            value: falcoeye
        image: falcoeye-workflow:latest
        imagePullPolicy: IfNotPresent
        name: falcoeye-workflow
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
