apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres-pv"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: falcoeye-temp-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/falcoeye-temp-pv"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-assets-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/user-assets-pv"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: falcoeye-assets-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Mi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/falcoeye-assets"