apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: postgres-pvc
spec:
   storageClassName: postgres-pv
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: falcoeye-temp-pvc
spec:
   storageClassName: falcoeye-temp-pv
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: user-assets-pvc
spec:
   storageClassName: user-assets-pv
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: falcoeye-assets-pvc
spec:
   storageClassName: falcoeye-assets-pv
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 2Gi
